
-- To Know all the Foreign Key in a List
SELECT
  TABLE_CONSTRAINTS.CONSTRAINT_NAME,
  TABLE_CONSTRAINTS.TABLE_NAME,
  TABLE_CONSTRAINTS.CONSTRAINT_TYPE,
  KEY_COLUMN_USAGE.REFERENCED_TABLE_NAME,
  KEY_COLUMN_USAGE.REFERENCED_COLUMN_NAME
FROM
  information_schema.TABLE_CONSTRAINTS
  INNER JOIN information_schema.KEY_COLUMN_USAGE ON (
    TABLE_CONSTRAINTS.CONSTRAINT_NAME = KEY_COLUMN_USAGE.CONSTRAINT_NAME
    AND TABLE_CONSTRAINTS.CONSTRAINT_SCHEMA = KEY_COLUMN_USAGE.CONSTRAINT_SCHEMA
  )
WHERE
 /* TABLE_CONSTRAINTS.TABLE_SCHEMA = 'category'
  AND */ TABLE_CONSTRAINTS.CONSTRAINT_TYPE = 'FOREIGN KEY';


SELECT
 *
FROM
  information_schema.TABLE_CONSTRAINTS
  INNER JOIN information_schema.KEY_COLUMN_USAGE ON (
    TABLE_CONSTRAINTS.CONSTRAINT_NAME = KEY_COLUMN_USAGE.CONSTRAINT_NAME
    AND TABLE_CONSTRAINTS.CONSTRAINT_SCHEMA = KEY_COLUMN_USAGE.CONSTRAINT_SCHEMA
  )
WHERE
 /* TABLE_CONSTRAINTS.TABLE_SCHEMA = 'category'
  AND */ TABLE_CONSTRAINTS.CONSTRAINT_TYPE = 'FOREIGN KEY';
